services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    restart: on-failure
    privileged: true
    user: root
    ports:
      - 8080:8080
    volumes:
      - "../../jenkins-volume:/var/jenkins_home"