version: "3"

services:
  sonarqube:
    image: sonarqube:8.9.10-community
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - ~/sonar-volume/sonarqube_data:/opt/sonarqube/data
      - ~/sonar-volume/sonarqube_extensions:/opt/sonarqube/extensions
      - ~/sonar-volume/sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - ~/sonar-volume/postgresql:/var/lib/postgresql
      - ~/sonar-volume/postgresql_data:/var/lib/postgresql/data
#volumes:
#  sonarqube_data:
#  sonarqube_extensions:
#  sonarqube_logs:
#  postgresql:
#  postgresql_data: