pipeline {
    environment {
        imageName = "mrbluetoo/simple-web-server:latest"
        customImage = ''
    }

    agent { label "jenkins-worker"}
    stages {


        stage('Start Container for Testing') {
            steps {
                script {
                    sh 'cd app'
                    sd 'ls -la'
                    sh 'docker compose rm -f'
                    sh 'docker compose up -d webapp'
                }
            }
        }

        stage('Run Tests') {
            steps {
                script {
                    sh 'docker exec webapp npm run test'
                }
            }
            post {
                success {
                    script {
                        sh 'docker compose down'
                    }
                }
                failure {
                    script {
                        sh 'docker compose down'
                    }
                }
            }
        }

        stage ('Push revision') {
            steps {
                script {
                    /* sh 'aws deploy push \
                            --application-name SimpleWebPage \
                            --description "This is a revision for the application SimpleWebPage" \
                            --ignore-hidden-files \
                            --s3-location s3://artifacts-demo-bucket/codedeploy_scripts.zip \
                            --source /infra/terraform/codedeploy_scripts/ \
                            --profile jenkins ' */
                    sh 'aws s3api list-objects --bucket artifacts-demo-bucket --profile jenkins'
                }
            }
        }

        /* stage('Build Image') {
            steps {
                script {
                    customImage = docker.build(imageName, "./app/")
                }
            }
        }

        stage('Push to Registry') {
            // when {
            //    branch "main"
            // }
            steps {
                script {
                    docker.withRegistry('', 'DockerhubCredentials') {
                        customImage.push()
                    }
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    sh 'aws deploy create-deployment --application-name SimpleWebPage --deployment-group-name SimpleWebPage_deployment_group --s3-location bucket=artifacts-demo-bucket,key=codedeploy_scripts.zip,bundleType=zip --profile jenkins'
                }
            }
        } */
    }
}