pipeline {
    agent any

    stages {
        stage('Init') {
            steps {
                script {
                    sh 'terraform -chdir=infra/terraform/ init'
                }
            }
        }

        stage('Plan') {
            steps {
                script {
                    sh 'bash ./infra/terraform/scripts/set_up_app_infra.sh plan'
                }
            }
        }

        stage('Apply/Destroy') {
            steps {
                script {
                    if (params.Action == 'apply') {
                        sh 'bash ./infra/terraform/scripts/set_up_app_infra.sh apply'
                    } else {
                        sh 'bash ./infra/terraform/scripts/set_up_app_infra.sh destroy'
                    }
                }
            }
        }
    }
}