pipeline {
    agent any

    stages {
        stage('Init') {
            steps {
                script {
                    sh 'terraform -chdir=infra/terraform/ init'
                }
            }
        }

        stage('Plan') {
            steps {
                script {
                    sh 'terraform -chdir=infra/terraform/ plan'
                }
            }
        }

        stage('Apply/Destroy') {
            steps {
                script {
                    if (params.Action == 'apply') {
                        sh 'terraform -chdir=infra/terraform/ apply --auto-approve'
                    } else {
                        sh 'terraform -chdir=infra/terraform/ destroy --auto-approve'
                    }
                }
            }
        }
    }
}