version: '3'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8081:8081"
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "80:80"