services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    restart: on-failure
    privileged: true
    ports:
      - 8080:8080
    volumes:
      - "./jenkins-volume:/var/jenkins_home"
      - "/bin/terraform:/bin/terraform"
      - "~/.aws:/var/jenkins_home/.aws"
      - "/var/run/docker.sock:/var/run/docker.sock"