services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    restart: on-failure
    privileged: true
    user: root
    ports:
      - 8080:8080
    volumes:
      - "./jenkins-volume:/var/jenkins_home"
      - "/bin/terraform:/bin/terraform"
      - "~/.aws:/var/jenkins_home/.aws"
      - "/usr/local/bin/aws:/usr/local/bin/aws"
      - "/var/run/docker.sock:/var/run/docker.sock"
      # - "/usr/bin/docker:/usr/bin/docker"
      # - "/usr/bin/com.docker.cli:/usr/bin/com.docker.cli"
      # - "/usr/bin/docker-compose:/usr/bin/docker-compose"
      # - "/usr/bin/docker-compose-v1:/usr/bin/docker-compose-v1"