global:
  scrape_interval: 15s
  # scrape_timeout: 10s
scrape_configs:
  - job_name: ec2_webserver
    sample_limit: 10000
    ec2_sd_configs:
      - region: us-east-1
        port: 9100
        filters:
          - name: tag:Name
            values:
              - webserver
              - staging-webserver