pipeline {
    environment {
        imageName = "mrbluetoo/simple-web-server:latest"
        customImage = ''
    }

    agent any
    stages {


        /* stage('Start Container for Testing') {
            steps {
                script {
                    sh 'cd app'
                    sh 'docker compose rm -f; docker compose up -d webapp'
                }
            }
        } */

        /* stage('Run Tests') {
            steps {
                script {
                    sh '''
                        cd app/src
                        npm install
                        npm test
                    '''
                }
            }
            post {
                success {
                    script {
                        sh 'docker compose down'
                    }
                }
                failure {
                    script {
                        sh 'docker compose down'
                    }
                }
            }
        } */

        stage('Build Image') {
            steps {
                script {
                    customImage = docker.build(imageName, "./app/")
                }
            }
        }

        stage('Push to Registry') {
            /* when {
                branch "main"
            } */
            steps {
                script {
                    docker.withRegistry('', 'DockerhubCredentials') {
                        customImage.push()
                    }
                }
            }
        }

        stage('Deploy') {
            steps {
                sshPublisher(
                    publishers: [
                        sshPublisherDesc(
                            configName: 'Ec2_instance_1',
                            transfers: [
                                sshTransfer(
                                    cleanRemote: false,
                                    excludes: '',
                                    execCommand: 'docker stop $(docker ps -a -q); docker rm $(docker ps -a -q); sudo docker run -p 80:8080 mrbluetoo/simple-web-server:latest ;exit 0',
                                    execTimeout: 30000,
                                    flatten: false,
                                    makeEmptyDirs: false,
                                    noDefaultExcludes: false,
                                    patternSeparator: '[, ]+',
                                    remoteDirectory: '',
                                    remoteDirectorySDF: false,
                                    removePrefix: '',
                                    sourceFiles: ''
                                )
                            ],
                            usePromotionTimestamp: false,
                            useWorkspaceInPromotion: false,
                            verbose: false
                        ),
                    ]
                )

                sshPublisher(
                    publishers: [
                        sshPublisherDesc(
                            configName: 'Ec2_instance_2',
                            transfers: [
                                sshTransfer(
                                    cleanRemote: false,
                                    excludes: '',
                                    execCommand: 'docker stop $(docker ps -a -q); docker rm $(docker ps -a -q); sudo docker run -p 80:8080 mrbluetoo/simple-web-server:latest ;exit 0',
                                    execTimeout: 30000,
                                    flatten: false,
                                    makeEmptyDirs: false,
                                    noDefaultExcludes: false,
                                    patternSeparator: '[, ]+',
                                    remoteDirectory: '',
                                    remoteDirectorySDF: false,
                                    removePrefix: '', sourceFiles: ''
                                )
                            ],
                            usePromotionTimestamp: false,
                            useWorkspaceInPromotion: false,
                            verbose: false
                        )
                    ]
                )
            }
        }
    }
}